---
name: Namaste Workflow
on:
  push:
    branches:
      - main
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say namaste to user
        run: echo "Namaste User"
      - name: say namaste to username
        run: echo "Namste to $username"

        
        
  
