name: portfolio

on:
    
  push:
    branches:
      - main
  workflow_dispatch:


permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .   # ✅ THIS IS REQUIRED

      - name: Deploy to Github pages
        id: deployment   # ✅ Needed for URL output
        uses: actions/deploy-pages@v4